- name: deploy to tomcat
  hosts: web
  become: yes
  
  tasks:
    - name: copy to tomcat webapps
      copy:
        src: "/var/snap/jenkins/5047/workspace/t6/target/t6.war"
        dest: "/opt/tomcat/webapps/t6.war"
        remote_src: no
      
    - name: restart tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh || true
        sleep 5
        /opt/tomcat/bin/startup.sh
